server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: client-service
              uri: lb://client-service
              predicates:
                - Path=/clients/**

            - id: produit-service
              uri: lb://produit-service
              predicates:
                - Path=/produits/**

            - id: commande-service
              uri: lb://commande-service
              predicates:
                - Path=/commandes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: gateway