services:

  discovery:
    build: ./service-discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  gateway:
    build: ./getway-service
    container_name: getway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    networks:
      - microservices-network

  client:
    build: ./client-service
    container_name: client
    ports:
      - "8081:8081"
    depends_on:
      - discovery
    networks:
      - microservices-network

  produit:
    build: ./produit-service
    container_name: produit
    ports:
      - "8083:8083"
    depends_on:
      - discovery
    networks:
      - microservices-network

  commande:
    build: ./commande-service
    container_name: commande
    ports:
      - "8082:8082"
    depends_on:
      - discovery
      - client
      - produit
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

